default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: search_admin_development
  username: search_admin
  password: search_admin
  url: <%= ENV["DATABASE_URL"]%>

test: &test
  <<: *default
  database: search_admin_test
  username: search_admin
  password: search_admin
  url: <%= ENV["TEST_DATABASE_URL"]%>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
